# Generated by Django 4.2.6 on 2024-01-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_answer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/users/default-avatar.jpg', null=True, upload_to=''),
        ),
    ]
